/*
 */
package oolite.starter.ui;

import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import javax.swing.text.html.HTMLDocument;
import org.apache.commons.io.IOUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * A panel presenting information about this project.
 * 
 * @author hiran
 */
public class AboutPanel extends javax.swing.JPanel {
    private static final Logger log = LogManager.getLogger();

    /**
     * Creates new form AboutPanel.
     */
    public AboutPanel() {
        initComponents();
    }

    /**
     * Creates new form AboutPanel.
     */
    public AboutPanel(String contentType, String content) {
        initComponents();
        jEditorPane1.setContentType(contentType);
        jEditorPane1.setText(content);

        jEditorPane1.addHyperlinkListener(new HyperLinkListener());
        jEditorPane1.setCaretPosition(0);
    }

    /**
     * Creates new form AboutPanel.
     */
    public AboutPanel(String contentType, URL url) throws IOException {
        initComponents();
        jEditorPane1.setContentType(contentType);
        
        String content = IOUtils.toString( getClass().getResource("/about.html"), StandardCharsets.UTF_8);
        jEditorPane1.setText(content);
        if ("text/html".equals(contentType)) {
            HTMLDocument doc = (HTMLDocument)jEditorPane1.getDocument();
            doc.setBase(url);
        }

        jEditorPane1.addHyperlinkListener(new HyperLinkListener());
        jEditorPane1.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jEditorPane1.setEditable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
