/*
 */
package oolite.starter.ui;

import java.util.List;
import javax.swing.DefaultListModel;
import oolite.starter.ExpansionManager;
import oolite.starter.model.Command;

/**
 *
 * @author hiran
 */
public class ExpansionManagerPanel extends javax.swing.JPanel implements ExpansionManager.ExpansionManagerListener {
    
    private transient ExpansionManager data;

    /**
     * Creates new form ExpansionManagerPanel.
     */
    public ExpansionManagerPanel() {
        initComponents();
        jList1.setCellRenderer(new CommandCellRenderer());
    }
    
    
    /**
     * Sets the data to be displayed.
     * 
     * @param em the expansionManager
     */
    public void setData(ExpansionManager data) {
        this.data = data;
        data.addExpansionManagerListener(this);
        update();
    }
    
    protected void update() {
        if (data == null) {
            jTextField1.setText("");
            jList1.setModel(new DefaultListModel<Command>());
        } else {
            String s = String.valueOf(data.getStatus());
            if (!data.getCommands().isEmpty()) {
                s = s + " (" + data.getCommands().size() + ")";
            }
            jTextField1.setText(s);
            DefaultListModel dlm = new DefaultListModel<Command>();
            dlm.addAll(data.getCommands());
            jList1.setModel(dlm);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jLabel1.setText("Status");

        jTextField1.setEditable(false);
        jTextField1.setText("jTextField1");

        jLabel2.setText("Queue");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Command> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateStatus(ExpansionManager.Status status, List<Command> queue) {
        update();
    }
}
