/*
 */
package oolite.starter.ui2;

import javax.swing.DefaultListModel;
import oolite.starter.Oolite;
import oolite.starter.model.OoliteFlavor;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * A panel to present Flavors to the user and allow him to install them.
 *
 * @author hiran
 */
public class FlavorsPanel extends javax.swing.JPanel {
    private static final Logger log = LogManager.getLogger();
    
    private Oolite oolite;
    
    DefaultListModel<OoliteFlavor> model;

    /**
     * Creates new form FlavorsPanel.
     */
    public FlavorsPanel() {
        log.debug("FlavorsPanel()");
        initComponents();
        jList1.setCellRenderer(new OoliteFlavorListCellRenderer());
    }
    
    /**
     * Sets the oolite instance to retrieve data from.
     * 
     * @param oolite the instance
     */
    public void setOolite(Oolite oolite) {
        log.debug("setOolite({})", oolite);
        this.oolite = oolite;
        
        try {
            model = new DefaultListModel<>();
            model.addAll(oolite.getFlavorList());        
            jList1.setModel(model);
        } catch (Exception e) {
            log.error("Could not load flavors", e);
            model = null;
            jList1.setModel(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<OoliteFlavor> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
