/*
 */
package oolite.starter.ui2;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.border.BevelBorder;
import javax.swing.border.CompoundBorder;
import javax.swing.border.LineBorder;
import oolite.starter.model.OoliteFlavor;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author hiran
 */
public class OoliteFlavorListCellRenderer extends javax.swing.JPanel implements ListCellRenderer<OoliteFlavor> {
    private static final Logger log = LogManager.getLogger();
    
    //private final Border emtpyBorder = new EmptyBorder(4, 2, 4, 4);
    //private final Border normalBorder = new CompoundBorder(new MatteBorder(0, 4, 0, 0, getBackground()), emtpyBorder);
    //private final Border warningBorder = new CompoundBorder(new MatteBorder(0, 4, 0, 0, Color.ORANGE), emtpyBorder);
    //private final Border problemBorder = new CompoundBorder(new MatteBorder(0, 4, 0, 0, Color.RED), emtpyBorder);
    
    /**
     * Creates new form OoliteFlavorListRenderer.
     */
    public OoliteFlavorListCellRenderer() {
        initComponents();
        editor = new JEditorPane();
        editor.setEditable(false);
        editor.setOpaque(false);
        add(editor, BorderLayout.CENTER);
        setBorder(new CompoundBorder(new LineBorder(getBackground(), 8), new BevelBorder(BevelBorder.RAISED)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        add(jLabel1, java.awt.BorderLayout.LINE_START);

        editor.setEditable(false);
        editor.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(editor);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getListCellRendererComponent(JList<? extends OoliteFlavor> list, OoliteFlavor data, int i, boolean isSelected, boolean isFocused) {
        jLabel1.setIcon(new ImageIcon(data.getImage()));
        
        StringBuilder sb = new StringBuilder("<html>");
//        sb.append("<table width=\"100%\" border=\"1\">");
//        sb.append("<tr>");
//        //sb.append("<td>");
//        //sb.append("<img src=\"").append(data.getImageUrl()).append("\"></img>");
//        //sb.append("</td>");
//        sb.append("<td width=\"*\">");
        sb.append("<p><b>");
        sb.append(data.getName());
        sb.append("</b></p><p>");
        sb.append(data.getDescription());
        sb.append("</p>&nbsp;");
//        sb.append("</td></tr>");
//        sb.append("</table>");
        sb.append("</html>");
        
        log.trace("text={}", sb);
        editor.setContentType("text/html");
        editor.setText(sb.toString());
        
        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        setEnabled(list.isEnabled());

        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
